apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-application
  labels:
    app: trend-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-application
  template:
    metadata:
      labels:
        app: trend-application
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: trend-application
          image: franklinmoses07/trend-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80